on:
  push:
    branches:
      - "master"

name: Lint

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP 7.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          tools: phplint, phpstan, phpcpd:4, phpcs

      - name: Run composer
        run: composer install --ignore-platform-reqs --prefer-dist

      - name: Run phplint
        run: phplint -c build/config/.phplint.yml

      - name: Run phpstan
        run: phpstan analyse -c build/config/phpstan.neon --no-progress

      - name: Run phpcs
        run: phpcs -q --standard=PSR2 src/

      - name: Run phpcpd
        run: phpcpd src/
